# -*- coding: utf-8 -*-
"""Untitled13.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/141gUrolAelPZVJ3Gqj59g1JxBZhR1CCV
"""

import ee
ee.Authenticate()
ee.Initialize(project='ee-kocakiruygarege')

import ee
import numpy as np
import matplotlib.pyplot as plt
import plotly.graph_objects as go
import geemap

ee.Initialize(project='ee-kocakiruygarege')

dem = ee.Image("USGS/SRTMGL1_003")

region = ee.Geometry.Polygon([
    [[-107.61, 37.61], [-107.57, 37.61], [-107.57, 37.63], [-107.61, 37.63], [-107.61, 37.61]]
])

dem_clip = dem.clip(region)

slope = ee.Terrain.slope(dem_clip)
aspect = ee.Terrain.aspect(dem_clip)

elevation_data = geemap.ee_to_numpy(dem_clip, region=region, bands=['elevation'])

if elevation_data is not None:
    elevation_data = np.squeeze(elevation_data)
else:
    raise ValueError("DEM Data Not Loaded!")

plt.figure(figsize=(8,6))
plt.imshow(elevation_data, cmap='terrain', extent=[-107.61, -107.57, 37.61, 37.63])
plt.colorbar(label="Elevation (m)")
plt.title("2D Terrain Topography - Windom Peak")
plt.xlabel("Longitude")
plt.ylabel("Latitude")
plt.show()

x = np.linspace(-107.61, -107.57, elevation_data.shape[1])
y = np.linspace(37.61, 37.63, elevation_data.shape[0])
X, Y = np.meshgrid(x, y)

fig = go.Figure(data=[go.Surface(z=elevation_data, x=X, y=Y, colorscale='Earth')])
fig.update_layout(title="3D Terrain Model - Windom Peak", autosize=True)
fig.show()

import ee
import numpy as np
import matplotlib.pyplot as plt
import plotly.graph_objects as go
import geemap

ee.Initialize(project='ee-kocakiruygarege')

dem = ee.Image("USGS/SRTMGL1_003")

center = ee.Geometry.Point([-107.591, 37.621])

region = center.buffer(10000)

dem_clip = dem.clip(region)

slope = ee.Terrain.slope(dem_clip)
aspect = ee.Terrain.aspect(dem_clip)

elevation_data = geemap.ee_to_numpy(dem_clip, region=region, bands=['elevation'])

if elevation_data is not None:
    elevation_data = np.squeeze(elevation_data)
else:
    raise ValueError("DEM Data Not Loaded!")

# 2D Topografik Harita Çizimi
plt.figure(figsize=(10, 8))
plt.imshow(elevation_data, cmap='terrain', extent=[-107.7, -107.5, 37.55, 37.69])
plt.colorbar(label="Elevation (m)")
plt.title("2D Terrain Topography - Windom Peak (10 km Area) on 5ft")
plt.xlabel("Longitude")
plt.ylabel("Latitude")
plt.show()

x = np.linspace(-107.7, -107.5, elevation_data.shape[1])
y = np.linspace(37.55, 37.69, elevation_data.shape[0])
X, Y = np.meshgrid(x, y)

fig = go.Figure(data=[go.Surface(z=elevation_data, x=X, y=Y, colorscale='Earth')])
fig.update_layout(title="3D Terrain Model - Windom Peak (10 km Area)", autosize=True)
fig.show()